### ISSUE TITLE
model.predict missing id remapping in lesson 4?

### ISSUE THREAD

**Issue by rrva** [fastai/courses#100]
Regarding deeplearning 1, lesson 4, I am trying to understand if my neural net model for collaborative filtering currently generates predictions as expected, taking the RMSE value the training results in (around 0.8) into account. I got strange results, using this

From deeplearning1/nbs/lesson4.ipynb:

>We can use the model to generate predictions by passing a pair of ints - a user id and a movie id. For instance, this predicts that user #3 would really enjoy movie #6.
```model.predict([np.array([3]), np.array([6])])```

should this not be 

```model.predict([np.array([userid2idx[3]]), np.array([movieid2idx[6]])])```

since user id:s and movie id:s are remapped to continuous numbers?

**Comment by jph00** [comment]
Best to use the forums for asking questions.
