### ISSUE TITLE
fast-ai-remove.sh doesn't delete key pairs

### ISSUE THREAD

**Issue by superquest** [fastai/courses#114]
http://wiki.fast.ai/index.php/Starting_Over_with_AWS instructs us to manually delete key pairs when starting over ... but the `fast-ai-remove.sh` script doesn't do this. 

Assuming that `fast-ai-remove.sh` did everything necessary to start over when it didn't cost me a couple hours setting up ...

**Comment by jph00** [comment]
Thanks for the info. If you could send a PR, that would be helpful!
