### ISSUE TITLE
install-gpu.sh script uses DOS line-endings

### ISSUE THREAD

**Issue by dennda** [fastai/courses#17]
I had some trouble running the `install-gpu.sh` script on a ubuntu linux AWS instance:
For instance, it wouldn't correctly download some of the links and when it created the downloads folder, the name was `downloads?`. I found that copy-pasting the individual commands worked, which made me think that it's an issue with line endings, and indeed, the file uses DOS line endings.

I opened it in vim, executed `:set ff=unix`, saved it, reran it, and everything worked.

**Comment by racheltho** [comment]
Thank you.  I've updated the file format to unix now.
