### ISSUE TITLE
Raise an error if test_name='test' but the test folder is empty or doesn't exist.

### ISSUE THREAD

**Issue by Autodidact24** [fastai/courses#187]
When you define the data object and do provide `test_name='test'`
```
data = ImageClassifierData.from_csv(PATH, folder='train', csv_fname=f'{PATH}labels.csv',
                                    tfms=tfms, val_idxs=get_cv_idxs(n=4750), test_name='test', bs=12)
```
But, the test folder is empty or doesn't exist, this assignment results in the following error:
![image](https://user-images.githubusercontent.com/5631503/33839724-07d5a6d2-deb9-11e7-8e36-b96ddf96a9e0.png)
![image](https://user-images.githubusercontent.com/5631503/33839735-0e95f058-deb9-11e7-888e-1a08dd26fe04.png)

The function `read_dir()` in `dataset.py` is used to read the `test`. The function already contains a `TODO: warn or error if no files are found?`

read_dir() is only used to read the test data folder.

![image](https://user-images.githubusercontent.com/5631503/33839815-3d7addf2-deb9-11e7-9c2c-79da0da209cd.png)

![image](https://user-images.githubusercontent.com/5631503/33839828-44155c32-deb9-11e7-9ebc-7462e130dd42.png)

The function gets called only when `test_name` is `True`. I think this should raise a `FileNotFoundError` is it returns an empty list. Something like the following:

![image](https://user-images.githubusercontent.com/5631503/33839839-4a02b284-deb9-11e7-9088-6b9a4aac53c8.png)

That way the error message would be more explicit.

**Comment by Sangramsingkayte** [comment]
raise RuntimeError("{} doesn't exist.".format(d))
RuntimeError: /Users/sangramsing/data/cmu_arctic/cmu_us_clb_arctic/wav doesn't exist.
