### ISSUE TITLE
Upgrad cuDNN tar.gz to 6.0

### ISSUE THREAD

**Issue by alexcombessie** [fastai/courses#188]
I ran into dependencies issues with the Theano backend. Since Theano is no longer developed, I chose to go with tensorflow. It was quite simple (edit the keras.json file to replace theano by tensorflow). But the latest version of tensorflow-gpu available through pip requires cuDNN 6.0. I had to manually switch (see https://stackoverflow.com/questions/38137828/how-do-i-update-cudnn-to-a-newer-version). Why not update the tar.gz on http://files.fast.ai/files/cudnn.tgz? No changes needed to https://github.com/fastai/courses/blob/master/setup/install-gpu.sh in this case.

**Comment by ashishm-io** [comment]
Requested a pull update here: 
https://github.com/fastai/courses/pull/189
