### ISSUE TITLE
Unreadable Notebook: lesson1

### ISSUE THREAD

**Issue by Sri2790** [fastai/courses#198]
Hi,
Im getting the following error when i open the file.

Unreadable Notebook: C:\Users\Sri\Music\lesson1.ipynb NotJSONError('Notebook does not appear to be JSON: u\'<!DOCTYPE html>\\n<html lang="en">\\n <h...',)

Thank you!!

**Comment by ehughes29** [comment]
Hi Everyone,

I'm getting a similar error
Unreadable Notebook: /home/nbuser/courses/fastai/deeplearning1/nbs/lesson1_testing.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)

Thanks,

**Comment by Sri2790** [comment]
In windows if you download using save as link it will be downloaded as html. We should clone and download
