### ISSUE TITLE
./setup_p2.sh: line 119: syntax error: unexpected end of file error on mac

### ISSUE THREAD

**Issue by quansun** [fastai/courses#20]
Hi, this is a great DL course, thanks very much!

I got "./line 119: syntax error: unexpected end of file" when trying to run the setup_p2 script on a mac machine. I have tried to use dos2unix and the method described in https://github.com/fastai/courses/issues/17

but didn't fix the error. 

Have you seen a similar error? Thanks!

**Comment by TheMadGator** [comment]
I have had the same problem and have not been able to resolve it.

**Comment by quansun** [comment]
Problem fixed.
See 
https://github.com/fastai/courses/issues/21
