### ISSUE TITLE
Syntax problem with Setup_p2.sh file...prior version works fine

### ISSUE THREAD

**Issue by TheMadGator** [fastai/courses#21]
I have been struggling and leaving messages in the forum, but could not get setup_p2.sh to work for me.  I went into history and downloaded the prior version and it works fine.  I believe when the last change was made a syntax error was created.

**Comment by renatocron** [comment]
Can you run `git pull` and try again? 

10 hours ago was merged one fix for this script (https://github.com/fastai/courses/pull/18/files) 

I would try myself, but I need go to work right now!

**Comment by quansun** [comment]
Thanks. The latest script worked fine now.
