### ISSUE TITLE
p2 instance -  nvidia-smi - mismatch versions

### ISSUE THREAD

**Issue by yonidavidson** [fastai/courses#25]
When running the p2 script I tried nvidia-smi and got an error.

**Comment by moezzie** [comment]
Hey yonidavidson,

What kind of error are you seeing.
Could you please provide the error message?

**Comment by racheltho** [comment]
It's better to ask this sort of question on [the forums](http://forums.fast.ai/).  Also, please see this wiki post on [how to ask for help](http://wiki.fast.ai/index.php/How_to_ask_for_Help) in a way that will allow others to most quickly and effectively be able to help you.
