### ISSUE TITLE
Theano: no GPU is abailable

### ISSUE THREAD

**Issue by moezzie** [fastai/courses#26]
Hi,

While following the guide to set up a P2 instance I'm running into an error when trying to import Theano in a Jupyter nodebook in the very last step of the AWS tutorial.

This P2 instance is running in Ireland (eu-west-1).
I've tried it with two separate instances with the same result.

    import theano
```WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: Unable to get the number of gpus available: CUDA driver version is insufficient for CUDA runtime version)```

Here is the output of nvidia-smi:

    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |===============================+======================+======================|
    |   0  Tesla K80           Off  | 0000:00:1E.0     Off |                    0 |
    | N/A   25C    P0    71W / 149W |      0MiB / 11439MiB |    100%      Default |
    +-------------------------------+----------------------+----------------------+
    
    +-----------------------------------------------------------------------------+
    | Processes:                                                       GPU Memory |
    |  GPU       PID  Type  Process name                               Usage      |
    |=============================================================================|
    |  No running processes found                                                 |
    +-----------------------------------------------------------------------------+

Have i missed a step or somewhere?

**Comment by moezzie** [comment]
Solved:

Rebooting the instance fixed the problem.

I've since tried to replicate the issue on yet another fresh instance. This time it worked fine from the start.
So there does not seem to be a problem after all.
Could have been a temporary AWS problem?

**Comment by renatocron** [comment]
It's a bug somewhere we don't know. The lasted script is doing the reboot
for you

**Comment by glyphx** [comment]
I had gotten the same error when I was using cnmem >= .8 on my gtx 980 on my own system when doing cpu_gpu or mnist.  So, if anything, this error output seems to be displayed for any reason including being out of memory.

**Comment by ramtest55** [comment]
Yes! on personal computer out of memory is coming
