### ISSUE TITLE
setup_p2.sh error

### ISSUE THREAD

**Issue by ramtest55** [fastai/courses#27]
After starting instance

1.type in cmd "python"
2.import theano
Wait for long time ..... 

nvidia-smi gives below thing

Failed to initialize NVML: Driver/library version mismatch
```

ubuntu@ip-10-0-0-4:~$ python
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import theano
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: Unable to get the number of gpus available: no CUDA-capable device is detected)
>>> exit()
ubuntu@ip-10-0-0-4:~$ nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
ubuntu@ip-10-0-0-4:~$ exit

```

May be cuDNN library causing problem. Can you please fix this bug so We can use this script to run keras on AWS

**Comment by jerminal** [comment]
The same problem :(

**Comment by racheltho** [comment]
@ramtest55 @jerminal Questions like this are better asked on [the forum](http://forums.fast.ai/).  How to troubleshoot this particular error has already been answered on the forum and in the [FAQ on the fast.ai wiki](http://wiki.fast.ai/index.php/Frequently_Asked_Questions).
