### ISSUE TITLE
get_data() takes path as argument for lesson2

### ISSUE THREAD

**Issue by yinleon** [fastai/courses#31]
From the current version of utils.py it looks like `get_data()` takes a directory path as an arg, rather than a batches-like object.

The video and notebook use `val_batches` and `batches`,  did the function change?

For the current version of `get_data()`,  shouldn't it look more like this:
`val_data = get_data(path + 'valid')`
`trn_data = get_data(path + 'train')`

**Comment by jph00** [comment]
Yes that's right.
