### ISSUE TITLE
Add /usr/local/cuda/bin to PATH ?

### ISSUE THREAD

**Issue by avdd** [fastai/courses#4]
I'm trying to get this going on Azure using the appropriate instructions.

Should the install-gpu script add /usr/local/cuda/bin to my PATH ?

See [this forum message](http://forums.fast.ai/t/reduce-size-of-volume/149/21) (`nvcc compiler not found on $PATH`) and response linking to CUDA FAQ.

**Comment by racheltho** [comment]
Good catch!  We've just updated the script to do so
