### ISSUE TITLE
An error occurred (MissingParameter) when calling the CreateTags operation: The request must contain the parameter resourceIdSet

### ISSUE THREAD

**Issue by eayoungs** [fastai/courses#49]
I'm getting an error with the `setup_p2.sh` shell script. I don't know what this parameter refers to. Is this something new? In the text of the shell script I see many _export_ calls that have a variable with 'Id' in the name but that specific variable is not found on searching.

Thx

Eric

**Comment by jph00** [comment]
Please ask on the forum.
