### ISSUE TITLE
setup_p2.sh fail to create instance

### ISSUE THREAD

**Issue by gouyl** [fastai/courses#54]
when i  bash setup_p2.sh  as the vedio said, it just don't work, and the error shown:

An error occurred (InvalidKeyPair.NotFound) when calling the RunInstances operation: The key pair 'aws-key-fast-ai' does not exist

An error occurred (MissingParameter) when calling the CreateTags operation: The request must contain the parameter resourceIdSet

could help me? thanks

**Comment by yoiang** [comment]
@gouyl did you resolve the issue? I am running into the same problem

**Comment by swordspoet** [comment]
I have met the same situation with you, the error shown:

An error occurred (InstanceLimitExceeded) when calling the RunInstances operatio                                                                                                                           n: You have requested more instances (1) than your current instance limit of 0 a                                                                                                                           llows for the specified instance type. Please visit http://aws.amazon.com/contac                                                                                                                           t-us/ec2-request to request an adjustment to this limit.

An error occurred (MissingParameter) when calling the CreateTags operation: The                                                                                                                            request must contain the parameter resourceIdSet
Waiting for instance start...

**Comment by smith-kyle** [comment]
I was able to fix the issue by first running
```
sudo rm ~/.ssh/aws-key-fast-ai.pem
```
