### ISSUE TITLE
Guys, vgg_16.py has duplicate import 

### ISSUE THREAD

**Issue by pepinu** [fastai/courses#60]
In courses/deeplearning1/nbs/vg16.py line 9 and line 12 import get_file twice 
```
from keras.utils.data_utils import get_file
from keras import backend as K
from keras.layers.normalization import BatchNormalization
from keras.utils.data_utils import get_file
```

Cheers

**Comment by zarak** [comment]
@DiMesq Can you please respond to @racheltho's review? Thanks!
#46 
38defa21a805b8de0facb73458fc8f52ea4da0ed

**Comment by racheltho** [comment]
@pepinu @zarak  Thanks!  I have resolved it [here](https://github.com/fastai/courses/commit/1ea81c2c74851bbbd601c14585020df08451fac2)
