### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by tayler** [fastai/courses#61]
Hi,

I just went through the steps to set up the EC2 instance, and I'm glad it was so easy. Thanks for all the work you've done to make it so. 

I did notice that the video points to www.platform.ai/files for the AWS setup files. That helpfully points to http://course.fast.ai/start.html, which says the files are now here on github. Once I get to this repo, I see the `setup/` directory and can figure things out from there. It did take some investigating to see that I needed both `setup/setup_p2.sh` and `setup/setup_instance.sh`. Are there instructions with this somewhere? If not, I could submit a PR and add instructions to this repo. If you'd like me to do that, would you prefer the setup instructions in the main README.md or in a new `setup/README.md`?

**Comment by vicneanschi** [comment]
It would be helpful.

**Comment by rrwiyatn** [comment]
Hi I am new with AWS, just wanna make sure, once I am connected to my instance, do we need to install all the things that are required like tensorflow, theano, keras, etc. or are they pre-installed?

**Comment by manojee1** [comment]
Hi I wanted to follow up on this thread. are there  updated instructions on how to install the necessary files from github. I am lost here. Thanks!

**Comment by jph00** [comment]
Instructions in setup/README.md would be very much appreciated! :) Thanks for offering.
