### ISSUE TITLE
problem with the import module in utils.py

### ISSUE THREAD

**Issue by VinceShieh** [fastai/courses#63]
Hi, 
In utils.py there is
from keras.regularizers import l2, activity_l2, l1, activity_l1
but, I checked with keras package, there is no such methods as activity_l2/activity_l1

other than that, I also found the same problem with
from keras.utils.layer_utils import layer_from_config

I wonder what the problems might be on my end.
thanks.

**Comment by AMilkov** [comment]
@VinceShieh 

Keras got to version 2.0 and there are few breaking changes.  
So activity_l2/activity_l1 become simply `l2` and `l1`

**Comment by VinceShieh** [comment]
yep, I just found out. thanks. and it seems there are also incompatible issues with theano

**Comment by VinceShieh** [comment]
if the compatibility issue is not gonna be fixed in time, you can use
pip uninstall keras
pip install keras==1.2.2
to stick to the previous release

**Comment by jph00** [comment]
It's not going to be fixed - we only support the provided AWS AMI or setup scripts for this class. The next class will however update them.
