### ISSUE TITLE
TypeError in Session 2 notebook when calling get_data function

### ISSUE THREAD

**Issue by clu2033** [fastai/courses#7]
I get this traceback when trying to call the get_data helper function with val_batches as the argument. It works when I pass just the file path to the validation data though. Also, I have not been able to successfully run the training data cell because I run out of memory. Would it be possible to upload the bcolz files  for the training and validation sets for those of us on weaker CPUs?

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-331fe70a82bb> in <module>()
----> 1 val_data = get_data(val_batches)

/home/clu/Python/courses-master/deeplearning1/nbs/utils.py in get_data(path, target_size)
    133 
    134 def get_data(path, target_size=(224,224)):
--> 135     batches = get_batches(path, shuffle=False, batch_size=1, class_mode=None, target_size=target_size)
    136     return np.concatenate([batches.next() for i in range(batches.nb_sample)])
    137 

/home/clu/Python/courses-master/deeplearning1/nbs/utils.py in get_batches(dirname, gen, shuffle, batch_size, class_mode, target_size)
     89                 target_size=(224,224)):
     90     return gen.flow_from_directory(dirname, target_size=target_size,
---> 91             class_mode=class_mode, shuffle=shuffle, batch_size=batch_size)
     92 
     93 

/home/clu/anaconda3/lib/python3.5/site-packages/keras/preprocessing/image.py in flow_from_directory(self, directory, target_size, color_mode, classes, class_mode, batch_size, shuffle, seed, save_to_dir, save_prefix, save_format)
    288             dim_ordering=self.dim_ordering,
    289             batch_size=batch_size, shuffle=shuffle, seed=seed,
--> 290             save_to_dir=save_to_dir, save_prefix=save_prefix, save_format=save_format)
    291 
    292     def standardize(self, x):

/home/clu/anaconda3/lib/python3.5/site-packages/keras/preprocessing/image.py in __init__(self, directory, image_data_generator, target_size, color_mode, dim_ordering, classes, class_mode, batch_size, shuffle, seed, save_to_dir, save_prefix, save_format)
    556         if not classes:
    557             classes = []
--> 558             for subdir in sorted(os.listdir(directory)):
    559                 if os.path.isdir(os.path.join(directory, subdir)):
    560                     classes.append(subdir)

TypeError: argument should be string, bytes or integer, not DirectoryIterator`

**Comment by racheltho** [comment]
It's better to ask this sort of question on [the forums](http://forums.fast.ai/)
