### ISSUE TITLE
Creating infrastructure with Terraform

### ISSUE THREAD

**Issue by jkurz** [fastai/courses#84]
hello,

Was wondering if you would be interested in a PR that could create your AWS resources with Terraform. The scripts you have are nice, but there are ways to do this in a more common way that would allow for anyone to come in and run some simple terraform commands to get started.

I would be interested in helping out with this, but was just curious what your thoughts were.

Thanks for this awesome course. I just started and had this initial thought about the infrastructure creation in AWS.

**Comment by jkurz** [comment]
Some benefits of using Terraform for this course. 
* People who are used to doing things in AWS will most likely have some experience with it.
* One can easily see what is going to be created, without digging through the scripts
* Stay in line with community best practices
* Make it simpler to work for people who have multiple AWS profiles in their credentials file
* Allow for easier paths forward, when it comes to maintaining this course and keeping it on track to stay on the leading edge.

**Comment by zarak** [comment]
Hi @jkurz,

If you go ahead with this, you're welcome to fork [my project](https://github.com/zarak/fastai-vpc). Hopefully it can be useful just to get started.

**Comment by jph00** [comment]
Thanks for the idea. I actually prefer to minimize the layers of abstraction when it comes to setting things up, so that new users can get more of a sense of what's going on, and can debug things themselves better. 

Having said that, I'd be happy to *add* terraform scripts as an additional approach for those that are interested.

**Comment by jkurz** [comment]
make sense. I don't want to make this a priority, as it seems like not that many people are very interested in it. So I am going to close this issue. I want to focus on the course more than the infrastructure atm. When I started it just jumped out at me, that the process could be improved and made simpler, however it's not the main focus of this course and you are correct. The more things to learn, the harder it is to focus on what is really important. Once I am done with the course, I may back and send a PR for the additional tf scripts to get the infrastructure up. Thanks again @jph00
