### ISSUE TITLE
VGG batches path error - Lesson One

### ISSUE THREAD

**Issue by wlrider** [fastai/courses#99]
GitHub virgin here, but I found some errors that might be helpful to correct. 
When instructing the path to the sample data sets in lesson one, "train" and "valid" are concatenated onto the path as shown below.

`vgg = Vgg16()
batches = vgg.get_batches(path+'train', batch_size=batch_size)
val_batches = vgg.get_batches(path+'valid', batch_size=batch_size*2)
vgg.finetune(batches)
vgg.fit(batches, val_batches, nb_epoch=1)`

Also, in the visual portion:

`batches = vgg.get_batches(path+'train', batch_size=batch_size)
val_batches = vgg.get_batches(path+'valid', batch_size=batch_size)`

Both instances seem to need '/train' and '/valid' to avoid the following error:

`OSError: [Errno 2] No such file or directory: 'data/dogscats/sampletrain'
OSError: [Errno 2] No such file or directory: 'data/dogscats/samplevalid'`

Thank y'all for the wonderful opportunity to be a part of this amazing journey! =)

**Comment by wlrider** [comment]
I can't follow directions =)

**Comment by aymanshams07** [comment]
I don't I'm following directions well either. How did you manage to solve this?

**Comment by wlrider** [comment]
So its been awhile, but I believe I had put the folders in the wrong layer. IE: I had the train and valid folders one more folder structure deep vs at the path folder.....Hope this helps!

**Comment by alex-sanders** [comment]
Yes! I just added a backslash before /train and /valid and it worked.

```
batches = vgg.get_batches(path+'/train', batch_size=batch_size)
val_batches = vgg.get_batches(path+'/valid', batch_size=batch_size*2)
```
